inherits: haskell
sudo: required

package:
  name: hstox
  version: 0.0.1

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev

haskell:
  packages:
    - semdoc

script:
  after:
    - git checkout $TRAVIS_BRANCH
    - semdoc src/tox/Network/Tox.lhs spec.old.md
    - git checkout -qf FETCH_HEAD
    - semdoc src/tox/Network/Tox.lhs spec.new.md
    - gem install gist
    - diff -u spec.old.md spec.new.md > spec.md.diff || gist spec.md.diff
    - gem install mdl
    - mdl -w -s .md-style.rb spec.new.md
