language: generic

matrix:
  include:
    - env: JOB=hstox ENV=linux
      language: haskell
      ghc: 7.8
    - env: JOB=hstox ENV=android
      services:
        - docker

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      # Required for libstdc++-4.9, which is required for llvm-3.8.
      - ubuntu-toolchain-r-test
    packages:
      - clang-format-3.8
      - clang-tidy-3.8

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

install:      .travis/phase $JOB $ENV install
script:       .travis/phase $JOB $ENV script
after_script: .travis/phase $JOB $ENV after_script

notifications:
  irc: "chat.freenode.net#toktok-status"

branches:
  only:
    - master
