language: haskell
ghc: 7.8

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      # Required for libstdc++-4.9, which is required for llvm-3.8.
      - ubuntu-toolchain-r-test
    packages:
      - clang-format-3.8
      - clang-tidy-3.8

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

install:
  # Make sure the submodules are up-to-date.
  - (cd test/toxcore/libsodium && git checkout stable && git pull)
  - (cd test/toxcore/msgpack-c && git checkout master && git pull)
  - (cd test/toxcore/toxcore   && git checkout master && git pull)
  # Install libsodium into $HOME/.cabal/extra-dist.
  - tools/install-libsodium
  - EXTRA_DIRS="--extra-include-dirs=$HOME/.cabal/extra-dist/include --extra-lib-dirs=$HOME/.cabal/extra-dist/lib"
  - cabal install --only-dependencies $EXTRA_DIRS
  - cabal install codecov-haskell hpc-coveralls aeson-0.9.0.1
  - cabal install stylish-haskell hlint happy
#  - cabal install pandoc

script:
  - export LD_LIBRARY_PATH=$HOME/.cabal/extra-dist/lib
  - make
  # Make a temporary commit with just the submodules to avoid errors on diff
  # checking due to ref changes in submodules.
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis Builder"
  - >
      git commit --allow-empty -m'Submodule updates.' \
        test/toxcore/libsodium \
        test/toxcore/msgpack-c \
        test/toxcore/toxcore
  - git diff --exit-code

after_script:
  - codecov-haskell hstox
  - hpc-coveralls   hstox
