language: haskell
ghc: 7.8

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

install:
  - tools/install-libsodium
  - EXTRA_DIRS="--extra-include-dirs=$HOME/.cabal/extra-dist/include --extra-lib-dirs=$HOME/.cabal/extra-dist/lib"
  - cabal install --only-dependencies $EXTRA_DIRS
  - cabal configure --enable-library-coverage $EXTRA_DIRS
  - cabal install codecov-haskell hpc-coveralls aeson-0.9.0.1
#  - cabal install pandoc stylish-haskell hlint

script:
  - export LD_LIBRARY_PATH=$HOME/.cabal/extra-dist/lib
  - cabal build
  - tools/run-tests hstox
  - tools/run-tests toxcore
  - tools/build-docs
  - git diff --exit-code

after_script:
  - mkdir -p dist/hpc/tix/hstox
  - hpc combine --exclude=Main --union testsuite.tix test-hstox.tix --output=dist/hpc/tix/hstox/hstox.tix
  - codecov-haskell hstox
  - hpc-coveralls   hstox
