language: haskell
ghc: 7.8

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

install:
  - tools/install-libsodium
  - EXTRA_DIRS="--extra-include-dirs=$HOME/.cabal/extra-dist/include --extra-lib-dirs=$HOME/.cabal/extra-dist/lib"
  - cabal install --only-dependencies $EXTRA_DIRS
  - cabal install codecov-haskell hpc-coveralls aeson-0.9.0.1
#  - cabal install pandoc stylish-haskell hlint

script:
  - export LD_LIBRARY_PATH=$HOME/.cabal/extra-dist/lib
  - make
  - git diff --exit-code

after_script:
  - codecov-haskell hstox
  - hpc-coveralls   hstox
